import "server-only";
import type { EmergencyView } from "@/lib/emergency";

/**
 * Single source of truth for the *content* of an exported record, shared by the
 * PDF (`pdf.ts`) and Word (`docx.ts`) renderers so both stay in lockstep. Only
 * the presentation layer differs between formats — the labels, order, and
 * "criticality" of each field live here.
 */

export interface RecordField {
  label: string;
  value: string;
  /** Critical fields (allergies present) get loud, alert-styled treatment. */
  critical?: boolean;
  /** Whether this field carries real data vs. a reassuring "none on file". */
  empty?: boolean;
}

export interface RecordSection {
  heading: string;
  fields: RecordField[];
}

function contactLine(c: {
  name: string | null;
  phone: string | null;
  relationship?: string | null;
}): string {
  if (!c.name && !c.phone) return "None on file";
  const who = [c.name, c.relationship ? `(${c.relationship})` : null]
    .filter(Boolean)
    .join(" ");
  return [who, c.phone].filter(Boolean).join(" · ");
}

/** The headline triage facts — name + the at-a-glance identity meta line. */
export function recordIdentity(view: EmergencyView): {
  name: string;
  meta: string;
} {
  const donor =
    view.organ_donor === true
      ? "Organ donor"
      : view.organ_donor === false
        ? "Not an organ donor"
        : null;
  const meta = [view.date_of_birth, view.sex, donor]
    .filter(Boolean)
    .join("  ·  ");
  return {
    name: view.patient_name || "Beacon patient",
    meta: meta || "No demographic details on file",
  };
}

/** The two loudest cards: blood group and allergies. */
export function recordCritical(view: EmergencyView): {
  bloodGroup: string;
  allergies: RecordField;
} {
  const hasAllergies = Boolean(view.allergies?.trim());
  return {
    bloodGroup:
      !view.blood_group || view.blood_group === "unknown"
        ? "Unknown"
        : view.blood_group,
    allergies: {
      label: "Allergies",
      value: hasAllergies ? view.allergies : "No known allergies on file",
      critical: hasAllergies,
      empty: !hasAllergies,
    },
  };
}

/** The body sections, in display order, shared across formats. */
export function recordSections(view: EmergencyView): RecordSection[] {
  const sections: RecordSection[] = [
    {
      heading: "Clinical",
      fields: [
        {
          label: "Current medications",
          value: view.medications?.trim() || "None on file",
          empty: !view.medications?.trim(),
        },
        {
          label: "Medical conditions",
          value: view.medical_conditions?.trim() || "None on file",
          empty: !view.medical_conditions?.trim(),
        },
      ],
    },
  ];

  if (view.additional_notes?.trim()) {
    sections.push({
      heading: "Other notes",
      fields: [{ label: "Notes", value: view.additional_notes.trim() }],
    });
  }

  const contacts: RecordField[] = [
    {
      label: "Emergency contact",
      value: contactLine(view.emergency_contact),
      empty: !view.emergency_contact.name && !view.emergency_contact.phone,
    },
  ];
  if (view.emergency_contact_2.name || view.emergency_contact_2.phone) {
    contacts.push({
      label: "Second contact",
      value: contactLine(view.emergency_contact_2),
    });
  }
  if (view.primary_physician.name || view.primary_physician.phone) {
    contacts.push({
      label: "Primary doctor",
      value: contactLine({
        name: view.primary_physician.name,
        phone: view.primary_physician.phone,
      }),
    });
  }
  sections.push({ heading: "Contacts", fields: contacts });

  return sections;
}

/** Confidentiality line shown in the footer of every export. */
export const CONFIDENTIALITY_NOTICE =
  "Confidential medical record. Generated by Beacon for emergency use. Verify identity before relying on this information.";
