import type { Metadata } from "next";
import Link from "next/link";
import { SearchX, ShieldAlert, ShieldOff, Clock } from "lucide-react";

// Sensitive — must never be crawled or indexed.
export const metadata: Metadata = {
  title: "Emergency view",
  robots: { index: false, follow: false, nocache: true },
};
import { getCurrentProfile, isApprovedProvider } from "@/lib/auth";
import { readEmergencyProfile } from "@/lib/emergency";
import { checkRateLimit } from "@/lib/rate-limit";
import { TriageCard } from "@/components/emergency/triage-card";
import { DownloadPdfButton } from "@/components/emergency/download-pdf-button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { SignOutButton } from "@/components/sign-out-button";

/** Shared shell for the non-success states (kept visually quiet). */
function Notice({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex min-h-dvh items-center justify-center px-4 py-10">
      <div className="w-full max-w-md">{children}</div>
    </main>
  );
}

export default async function EmergencyPage({
  params,
}: {
  params: Promise<{ qr_token: string }>;
}) {
  const { qr_token } = await params;
  await checkRateLimit(`emergency:${qr_token}`, 20);

  // Middleware guarantees an authenticated user reaches this page.
  const session = await getCurrentProfile();
  if (!session) {
    // Defensive — should be handled by middleware.
    return (
      <Notice>
        <Alert variant="info">
          <ShieldAlert />
          <AlertTitle>Please sign in</AlertTitle>
          <AlertDescription>
            <Link href={`/provider/login?next=/e/${qr_token}`} className="underline">
              Sign in as a doctor
            </Link>{" "}
            to view emergency information.
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  // Authorisation: approved providers only (BUILD_SPEC §6, §7.4) → 403.
  if (!isApprovedProvider(session.profile)) {
    const pending = session.profile.role === "provider";
    return (
      <Notice>
        <Alert variant={pending ? "caution" : "critical"}>
          {pending ? <Clock /> : <ShieldAlert />}
          <AlertTitle>
            {pending ? "Awaiting approval" : "Access restricted"}
          </AlertTitle>
          <AlertDescription className="flex flex-col gap-3">
            {pending
              ? "Your provider account hasn't been approved yet. You'll be able to view emergency information once an administrator approves you."
              : "Only approved doctors can view emergency information."}
            <SignOutButton variant="outline" />
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  // Privileged read + audit log + notification. Captures who accessed it.
  // Unknown token → identical friendly 404-style response, no info leak (§7.2).
  const result = await readEmergencyProfile(qr_token, {
    id: session.user.id,
    name: session.profile.full_name,
    email: session.user.email ?? null,
  });

  if (result.status === "disabled") {
    return (
      <Notice>
        <Alert variant="caution">
          <ShieldOff />
          <AlertTitle>Emergency access is paused</AlertTitle>
          <AlertDescription className="flex flex-col gap-3">
            This person has temporarily turned off emergency access to their
            record. Please use another way to obtain their information.
            <Button asChild variant="outline" className="w-fit">
              <Link href="/provider">Back to provider home</Link>
            </Button>
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  if (result.status === "not_found") {
    return (
      <Notice>
        <Alert variant="default">
          <SearchX />
          <AlertTitle>Invalid or expired code</AlertTitle>
          <AlertDescription className="flex flex-col gap-3">
            This emergency code isn&apos;t valid. It may have been regenerated by
            its owner. Ask for an up-to-date code.
            <Button asChild variant="outline" className="w-fit">
              <Link href="/provider">Back to provider home</Link>
            </Button>
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  return (
    <main className="min-h-dvh bg-muted/40 px-4 py-6 sm:py-10">
      <TriageCard data={result.view} />
      <div className="mx-auto mt-4 w-full max-w-xl print:hidden">
        <DownloadPdfButton token={qr_token} />
      </div>
    </main>
  );
}
