import type { Metadata } from "next";
import Link from "next/link";
import { SearchX, ShieldOff } from "lucide-react";

// Sensitive — must never be crawled or indexed.
export const metadata: Metadata = {
  title: "Emergency view",
  robots: { index: false, follow: false, nocache: true },
};
import { getCurrentProfile, isApprovedProvider } from "@/lib/auth";
import { readEmergencyProfile } from "@/lib/emergency";
import { checkRateLimit } from "@/lib/rate-limit";
import { TriageCard } from "@/components/emergency/triage-card";
import { DownloadPdfButton } from "@/components/emergency/download-pdf-button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";

/** Shared shell for the non-success states (kept visually quiet). */
function Notice({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex min-h-dvh items-center justify-center px-4 py-10">
      <div className="w-full max-w-md">{children}</div>
    </main>
  );
}

export default async function EmergencyPage({
  params,
}: {
  params: Promise<{ qr_token: string }>;
}) {
  const { qr_token } = await params;
  await checkRateLimit(`emergency:${qr_token}`, 20);

  // No login required — a bystander in an emergency has no account. If the
  // viewer HAPPENS to be signed in as an approved provider, their real
  // identity is attributed in the audit log instead of "Anonymous scan", and
  // they get the PDF-download option (which keeps its own reason + gate).
  const session = await getCurrentProfile();
  const approvedProvider =
    session && isApprovedProvider(session.profile) ? session : null;

  // Privileged read + audit log + notification. Captures who accessed it
  // (or logs "Anonymous scan" when nobody's signed in). Unknown token →
  // identical friendly 404-style response, no info leak (§7.2).
  const result = await readEmergencyProfile(
    qr_token,
    approvedProvider
      ? {
          id: approvedProvider.user.id,
          name: approvedProvider.profile.full_name,
          email: approvedProvider.user.email ?? null,
        }
      : null,
  );

  if (result.status === "disabled") {
    return (
      <Notice>
        <Alert variant="caution">
          <ShieldOff />
          <AlertTitle>Emergency access is paused</AlertTitle>
          <AlertDescription className="flex flex-col gap-3">
            This person has temporarily turned off emergency access to their
            record. Please use another way to obtain their information.
            <Button asChild variant="outline" className="w-fit">
              <Link href="/">Back to Beacon</Link>
            </Button>
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  if (result.status === "not_found") {
    return (
      <Notice>
        <Alert variant="default">
          <SearchX />
          <AlertTitle>Invalid or expired code</AlertTitle>
          <AlertDescription className="flex flex-col gap-3">
            This emergency code isn&apos;t valid. It may have been regenerated by
            its owner. Ask for an up-to-date code.
            <Button asChild variant="outline" className="w-fit">
              <Link href="/">Back to Beacon</Link>
            </Button>
          </AlertDescription>
        </Alert>
      </Notice>
    );
  }

  return (
    <main className="min-h-dvh bg-muted/40 px-4 py-6 sm:py-10">
      <TriageCard data={result.view} />
      {approvedProvider && (
        <div className="mx-auto mt-4 w-full max-w-xl print:hidden">
          <DownloadPdfButton token={qr_token} />
        </div>
      )}
    </main>
  );
}
